### ISSUE TITLE
Output FASTA sequence headers throw away some information

### ISSUE THREAD

**Issue by niemasd** [a1kaul/TErex1.0#6]
Right now, the headers look like this:
`>7SLRNA;DF0000016.4;35.5;3e-10;+`

In other words, you're only keeping family name ("target name"), accession number ("acc"), bitscore ("bits"), e-value ("e-value"), and strand ("+"). However, I would recommend also saving "ali-st" (the position in the query sequence at which the hit starts), "ali-en" (the position in the query sequence at which the hit ends, and "description of target"

**Comment by aryakaul** [comment]
Kk! I'll update it

**Comment by aryakaul** [comment]
Done!
